name: Build ModoMorte24h Plugin

on:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: â˜• Instalar Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Clean local Maven repository cache
        run: rm -rf ~/.m2/repository/io/papermc

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: ðŸ§© Compilar o plugin com Maven
        run: mvn clean package --batch-mode

      - name: ðŸ“¦ Publicar o arquivo .jar como artefato
        uses: actions/upload-artifact@v4
        with:
          name: ModoMorte24h
          path: target/ModoMorte24h-*.jar
